name: SquidGame
main: com.vsrstudio.squidgame.SquidGame
version: 1.0
api-version: 1.20
author: VsrStudio
commands:
  join:
    description: Join the Squid Game.
  leave:
    description: Leave the Squid Game.
  start:
    description: Start the Squid Game.
permissions:
  squidgame.start:
    description: Allows starting the Squid Game.
    default: op
